image: atlassian/default-image:latest

pipelines:
  default:
    - step:
        deployment: production
        script:
          - echo "Deploying to production"
          - pipe: atlassian/ssh-run:0.2.2
            variables:
              SSH_USER: 'gorungo'
              SERVER: '77.222.60.50'
              COMMAND: '/var/www/gorungo/goback/deploy.sh'
