image: atlassian/default-image:latest

pipelines:
  default:
    - step:
        deployment: production
        script:
          - ssh root@77.222.60.50
          - sh deploy.sh
          - echo "Deploy step finished"
