image: atlassian/default-image:latest

pipelines:
  default:
    - step:
        deployment: production
        script:
          - cat ./deploy.sh | ssh -tt gorungo@77.222.60.50
          - echo "Deploy step finished"
